#' Subsetting 'projections' objects
#'
#' Two functions can be used to subset projections objects. The operator "[" can
#' be used as for matrices, using the syntax \code{x[i,j]} where 'i' is a subset
#' of dates, and 'j' is a subset of simulations.
#'
#' @author Thibaut Jombart \email{thibautjombart@@gmail.com}
#'
#'
#' @rdname subset
#'
#' @aliases "subset.projections" "[.projections"
#'
#' @seealso The \code{\link{project}} function to generate the 'projections'
#'   objects.
#'
#' @param x An projections object, generated by the function
#'   \code{\link{project}}.
#'



#' @export
#' @param i a subset of dates to retain
#' @param j a subset of groups to retain

"[.projections" <- function(x, i, j){
  if (missing(i)) {
    i <- TRUE
  }

  if (missing(j)) {
    j <- TRUE
  }

  out <- as.matrix(x)[i, j, drop = FALSE]
  rownames(out) <- attr(out, "dates") <- get_dates(x)[i]
  attr(out, "cumulative") <- attr(x, "cumulative")
  class(out) <- c("projections", "matrix")
  out
}
